#!/bin/bash

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
export NODE_ENV=production

SERVERNAME="hublin"
SERVERPATH="/srv/$SERVERNAME"
SERVERLOGPATH="$SERVERPATH/log"
FOREVERPATH="$SERVERLOGPATH/forever"

get_status () {
  [ -f $FOREVERPATH/$SERVERNAME.pid ] || return 1
  PID=`cat $FOREVERPATH/$SERVERNAME.pid`
  [ -z `ps -p $PID --no-headers | cut -d' ' -f2` ] && return 1
  return 0
}

status () {
  get_status
  _res=$?
  [ $_res -eq 0 ] && echo "hublin is running"
  [ $_res -eq 1 ] && echo "hublin is not running"
  exit $_res
}

start () {
  get_status
  _res=$?
  [ -d "$SERVERPATH/log/forever" ] || mkdir -p "$SERVERPATH/log/forever"
  [ $_res -eq 0 ] || exec forever --sourceDir=$SERVERPATH -p $FOREVERPATH -o $SERVERLOGPATH/$SERVERNAME-access.log -e $SERVERLOGPATH/$SERVERNAME-error.log --pidFile $FOREVERPATH/$SERVERNAME.pid --uid "$SERVERNAME" -a start server.js
}

stop () {
  get_status
  _res=$?
  [ $_res -eq 1 ] || forever stop "$SERVERNAME"
}

function help {
  echo "usage: /etc/init.d/hublin (start|stop|restart|status)"
}

case "$1" in
  start)
    start
  ;;

  stop)
    stop
  ;;

  restart)
    stop
    start
  ;;

  status)
    status
  ;;

  help)
    help
  ;;

  *)
    help
    exit 1
  ;;

esac

exit 0

